$currentDir = Get-Location
$buildDir = "build"
$shadersDir = ".\src\shaders"
$generatedHeader = "$buildDir\shaders_generated.hpp"

# 빌드 폴더 설정
if (Test-Path $buildDir) {
    Remove-Item -Recurse -Force $buildDir
}
New-Item -ItemType Directory -Path $buildDir

# 쉐이더 파일 읽기 및 동적 헤더 생성
Write-Host "Generating $generatedHeader..."

# 쉐이더 파일 내용을 읽어오는 함수 (이스케이프 불필요)
function Get-RawShaderContent {
    param(
        [Parameter(Mandatory=$true)]$FilePath
    )

    if (-not (Test-Path $FilePath)) {
        Write-Error "Shader file not found: $FilePath"
        return "// Error: File not found: $FilePath"
    }

    # Raw String Literal을 쓰기 때문에 원본 내용을 그대로 읽습니다.
    $content = Get-Content -Path $FilePath -Raw
    return $content
}

# 쉐이더 파일 검색 및 변환
$shaderFiles = Get-ChildItem -Path $shadersDir -Include *.vert, *.frag -File -Recurse
$shaderDeclarations = @()

foreach ($file in $shaderFiles) {
    $baseName = $file.BaseName
    $fileType = $file.Extension.TrimStart('.')
    
    # C++ 변수 이름 생성: NAME_TYPE_SHADER
    $variableName = "$($baseName)_$($fileType)_SHADER".ToUpper()
    
    Write-Host "  Processing $($file.Name) -> $($variableName)"

    $rawContent = Get-RawShaderContent $file.FullName
    
    # 중요: C++ Raw String Literal 문법인 R"(...)"을 사용합니다.
    # PowerShell에서 " 문자를 표현하기 위해 `"를 사용합니다.
    $declaration = "    // $($file.Name)`n    constexpr const char* $($variableName) = R`"($rawContent)`";"
    $shaderDeclarations += $declaration
}

# 모든 선언을 하나의 문자열로 결합
$allDeclarations = $shaderDeclarations -join "`n`n"

# shaders_generated.hpp 파일 내용 구성
$headerContent = @"
// This file is auto-generated by build.ps1. Do not edit manually.

#pragma once

namespace shaders {

$allDeclarations

}
"@

# 파일 쓰기
$headerContent | Out-File $generatedHeader -Encoding UTF8

Write-Host "$generatedHeader generated successfully with $($shaderFiles.Count) shader(s)."

# Visual Studio 환경 설정 및 컴파일
# 주의: 사용자의 환경에 맞춰 경로가 올바른지 확인하세요.
Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
Enter-VsDevShell -VsInstallPath "C:\Program Files\Microsoft Visual Studio\2022\Community" -DevCmdArguments "-arch=amd64 -host_arch=amd64"

Set-Location $currentDir

# Build main executable
# /D "SHADERS_GENERATED" 매크로 정의 확인
cl src\*.cpp /EHsc /std:c++20 /D "NDEBUG" /I ..\win-x64-msvc\include /I src /I build /Fo"build\\" /D "SHADERS_GENERATED" /Fe"build\4_1_fragment_shader.exe" /Fd"build\vc.pdb" /link /LIBPATH:..\win-x64-msvc\lib freeglut.lib glew32.lib opengl32.lib

$env:Path = $env:Path + ";$currentDir\..\win-x64-msvc\bin"

# Run main program
Write-Host "Running 4_1_fragment_shader..."
.\build\4_1_fragment_shader.exe
Write-Host "4_1_fragment_shader exited."