name: Clang-Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-clang-format
        restore-keys: |
          ${{ runner.os }}-apt-
    
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format
    
    - name: Check formatting
      run: |
        find . -path ./win-x64-msvc -prune -o \( -name '*.cpp' -o -name '*.hpp' -o -name '*.h' \) -type f -print | xargs clang-format --dry-run --Werror