name: Clang-Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache and install APT packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: clang-format
        version: 1.0
    
    - name: Check formatting
      run: |
        find . -path ./win-x64-msvc -prune -o \( -name '*.cpp' -o -name '*.hpp' -o -name '*.h' \) -type f -print | xargs clang-format --dry-run --Werror