name: Clang-Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: |
          ~/apt-cache
        key: ${{ runner.os }}-apt-clang-format-${{ hashFiles('.github/workflows/clang-format.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-clang-format-
    
    - name: Install clang-format
      run: |
        mkdir -p ~/apt-cache
        sudo apt-get update
        sudo apt-get install -y -o dir::cache::archives="$HOME/apt-cache" clang-format
    
    - name: Check formatting
      run: |
        find . -path ./win-x64-msvc -prune -o \( -name '*.cpp' -o -name '*.hpp' -o -name '*.h' \) -type f -print | xargs clang-format --dry-run --Werror